uploads = []
outputs = []

[[generated]]
id = "Z7d7MAedHeirDzM-ADvVo"
uri = "file://artifacts/streamvault-promo/public/geo-shapes.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vbT_dNj_m6u39B4WvkkfQ"
uri = "file://artifacts/streamvault-promo/public/trading-chart.png"
type = "image"
title = "generated_image"
